"""empty message

Revision ID: e672967f65f1
Revises: 53d0a4d0837c
Create Date: 2025-09-09 21:19:40.196152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e672967f65f1'
down_revision = '53d0a4d0837c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_account', sa.String(length=9), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_account'], ['users.account'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_account', sa.String(length=9), nullable=False))
        batch_op.drop_constraint(batch_op.f('records_user_account_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_account'], ['account'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['author_account'], ['account'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('records_user_account_fkey'), 'users', ['user_account'], ['account'])
        batch_op.drop_column('author_account')

    op.drop_table('logs')
    # ### end Alembic commands ###
