"""init

Revision ID: feb30989eb39
Revises: 
Create Date: 2025-09-05 17:44:04.315793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb30989eb39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('account', sa.String(length=9), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('account')
    )
    op.create_table('admins',
    sa.Column('account', sa.String(length=9), nullable=False),
    sa.ForeignKeyConstraint(['account'], ['users.account'], ),
    sa.PrimaryKeyConstraint('account')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_account', sa.String(length=9), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=7), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_account'], ['users.account'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    op.drop_table('admins')
    op.drop_table('users')
    # ### end Alembic commands ###
